---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ovtainxn/flashcards.programminghelp.org/
    - /usr/bin/pkill -9 lsnode >/dev/null 2>&1
    - /bin/cp -R client $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/rm -rf "${DEPLOYPATH}client/dist" || true
    - ~/nodevenv/flashcards.programminghelp.org/16/bin/npm install
    - ~/nodevenv/flashcards.programminghelp.org/16/bin/npm run postinstall
