---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ovtainxn/flashcards.programminghelp.org/
    - /bin/cp -R client $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/rm -rf "${DEPLOYPATH}client/dist" || true
    - source /home/ovtainxn/nodevenv/flashcards.programminghelp.org/16/bin/activate && cd /home/ovtainxn/flashcards.programminghelp.org
