---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ovtainxn/flashcards.programminghelp.org/
    - /bin/cp -R client $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/rm -r "${DEPLOYPATH}client/dist"
