name: CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu]
        node-version: [16.x,18.x,20.x]
    name: ${{ matrix.os }} - ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Client Dependencies
        working-directory: './client'
        run: npm ci
      - name: Run Vitest
        working-directory: './client'
        run: npm test 
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to cPanel
        uses: pinkasey/cpanel-deploy-action@v1.1.2
        with:
          hostname: "https://rssd9243.webaccountserver.com"
          repository_root: "/home/ovtainxn/repositories/flashcards"
          branch: main
          cpanel_username: "ovtainxn"
          cpanel_token: "${{ secrets.CPANEL_TOKEN }}"